language: python
os: linux

services:
  - xvfb

addons:
  chrome: stable

python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9-dev"

install:
  - pip install git+https://github.com/a-maliarov/melenium

before_script:
  - pip install webdriver_manager
  - pip install coverage
  - pip install codecov

script:
  - coverage run tests/test_main.py

after_success:
  - codecov
